### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by KevinBulme** [jimschubert/chrome-random-newtab#1]
Hello !

I've found this repo after a while and would like to publish (as a chrome extension) a very similar extension, would that sound good to you ?

**Comment by jimschubert** [comment]
Yeah, you're more than welcome to use this code as the basis for another extension.

**Comment by KevinBulme** [comment]
Thank you very much !
I published the extension here : https://chrome.google.com/webstore/detail/random-new-tab-page/djehcdbnpljkodikcpgfaihecidkgjie
